class_id: diatom_chain_3
display_name: Diatom Chain 3 (low mag)
group: Diatoms
optics: [low-mag]
one_liner: "Low-magnification diatom-chain, distinguished by having a relatively straight chain shape."
defining_characteristics: "A low-magnification morphotype class for a straight, chain-forming diatoms. This is a catch-all group for chained diatoms that form a straight chains and cannot be keyed into other classes. Key features: straight diatom chains."
distinguishing_from:
  - class: diatom_chain_1
    note: "Morphotype 1 diatom chains have large, thick setae."
  - class: diatom_chain_2
    note: "Morphotype 2 diatom chains form helical or spiral chains."
  - class: thalassiosira
    note: "If seperated disc-shaped chained cells, should be labeled as thalassiosira."
