#!/usr/bin/env python3
"""
build_pages.py — generate the Planktivore guide from structured data.

Single source of truth = each class's `meta.yml` + its `ideal/` and
`challenging/` image folders. This script renders that data into:

  * classes/<id>/index.qmd   -> a page in the HTML website
  * guide.qmd                -> a single combined document for the PDF build

The slide deck (slides/training.qmd) is authored separately.

Do NOT hand-edit the generated *.qmd files — edit meta.yml and re-run:

    python scripts/build_pages.py

Requires: pyyaml  (pip install -r requirements.txt)
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

import yaml

IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".gif", ".webp"}
REPO_ROOT = Path(__file__).resolve().parent.parent
CLASSES_DIR = REPO_ROOT / "classes"

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/build_pages.py — do not edit by hand. "
    "Edit meta.yml and re-run the script. -->"
)


def collapse(text) -> str:
    """Collapse a YAML block scalar into a single clean line."""
    if text is None:
        return ""
    return " ".join(str(text).split())


def yaml_quote(text: str) -> str:
    """Make a string safe to sit inside double quotes in YAML front matter."""
    return collapse(text).replace('"', "'")


def find_images(class_dir: Path, subset: str) -> list[str]:
    folder = class_dir / subset
    if not folder.is_dir():
        return []
    files = [
        p.name
        for p in folder.iterdir()
        if p.is_file() and p.suffix.lower() in IMAGE_EXTS
    ]
    return sorted(files)


def image_grid(class_dir: Path, subset: str, meta: dict, path_prefix: str) -> str:
    """Render an image subset as a Quarto column layout of captioned figures."""
    names = find_images(class_dir, subset)
    if not names:
        return "_No images yet — add files to this folder._\n"
    notes = meta.get("image_notes") or {}
    ncol = min(3, len(names))
    lines = [f'::: {{layout-ncol="{ncol}"}}', ""]
    for name in names:
        rel = f"{subset}/{name}"
        caption = collapse(notes.get(rel, ""))
        src = f"{path_prefix}{rel}"
        lines.append(f"![{caption}]({src})")
        lines.append("")
    lines.append(":::")
    lines.append("")
    return "\n".join(lines)


def distinguishing_table(meta: dict) -> str:
    rows = meta.get("distinguishing_from") or []
    if not rows:
        return "_No look-alike classes recorded yet._\n"
    out = ["| Similar class | How to tell them apart |", "|---|---|"]
    for row in rows:
        cls = collapse(row.get("class", "")).replace("|", "\\|")
        note = collapse(row.get("note", "")).replace("|", "\\|")
        out.append(f"| **{cls}** | {note} |")
    out.append("")
    return "\n".join(out)


def references_list(meta: dict) -> str:
    refs = meta.get("references") or []
    if not refs:
        return "_No external references yet._\n"
    out = []
    for ref in refs:
        title = collapse(ref.get("title", "reference"))
        url = collapse(ref.get("url", ""))
        out.append(f"- [{title}]({url})" if url else f"- {title}")
    out.append("")
    return "\n".join(out)


def render_body(class_dir: Path, meta: dict, path_prefix: str) -> str:
    """Shared ##-level body used by both the web page and the PDF section."""
    optics = ", ".join(meta.get("optics") or []) or "unspecified"
    group = collapse(meta.get("group", "Unclassified"))
    parts = [
        f"**Group:** {group}  ·  **Optics:** {optics}",
        "",
        "## Defining characteristics",
        "",
        collapse(meta.get("defining_characteristics")),
        "",
        "## Distinguishing from similar classes",
        "",
        distinguishing_table(meta),
        "## Ideal images",
        "",
        image_grid(class_dir, "ideal", meta, path_prefix),
        "## Challenging images",
        "",
        image_grid(class_dir, "challenging", meta, path_prefix),
        "## References",
        "",
        references_list(meta),
    ]
    return "\n".join(parts)


def cover_image(class_dir: Path) -> str | None:
    for subset in ("ideal", "challenging"):
        imgs = find_images(class_dir, subset)
        if imgs:
            return f"{subset}/{imgs[0]}"
    return None


def load_classes() -> list[tuple[Path, dict]]:
    out = []
    for class_dir in sorted(CLASSES_DIR.iterdir()):
        if not class_dir.is_dir():
            continue
        if class_dir.name.startswith((".", "_")):
            continue
        meta_path = class_dir / "meta.yml"
        if not meta_path.exists():
            print(f"  ! skipping {class_dir.name}: no meta.yml", file=sys.stderr)
            continue
        with meta_path.open() as fh:
            meta = yaml.safe_load(fh) or {}
        out.append((class_dir, meta))
    return out


def write_class_page(class_dir: Path, meta: dict) -> None:
    display = collapse(meta.get("display_name", class_dir.name))
    subtitle = yaml_quote(meta.get("one_liner", ""))
    group = collapse(meta.get("group", "Unclassified"))
    cover = cover_image(class_dir)

    fm = [
        "---",
        f'title: "{display}"',
        f'subtitle: "{subtitle}"',
        f"categories: [{group}]",
    ]
    if cover:
        fm.append(f"image: {cover}")
    fm += ["---", "", GENERATED_BANNER, ""]

    body = render_body(class_dir, meta, path_prefix="")
    (class_dir / "index.qmd").write_text("\n".join(fm) + "\n" + body + "\n")


def write_guide_pdf(classes: list[tuple[Path, dict]]) -> None:
    fm = textwrap.dedent(
        """\
        ---
        title: "Planktivore Labelling Guide"
        subtitle: "Complete class reference"
        format:
          pdf:
            toc: true
            toc-depth: 2
            number-sections: true
            fig-pos: "H"
            geometry: margin=1in
        ---
        """
    )
    chunks = [fm, GENERATED_BANNER, ""]
    for class_dir, meta in classes:
        display = collapse(meta.get("display_name", class_dir.name))
        prefix = f"classes/{class_dir.name}/"
        chunks.append(f"\n# {display}\n")
        chunks.append(render_body(class_dir, meta, path_prefix=prefix))
    (REPO_ROOT / "guide.qmd").write_text("\n".join(chunks) + "\n")


def main() -> int:
    classes = load_classes()
    if not classes:
        print("No classes found under classes/.", file=sys.stderr)
        return 1
    for class_dir, meta in classes:
        write_class_page(class_dir, meta)
        print(f"  + classes/{class_dir.name}/index.qmd")
    write_guide_pdf(classes)
    print("  + guide.qmd")
    print(f"Done: {len(classes)} class(es).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
