#!/usr/bin/env python3
"""
build_pages.py — generate the Planktivore guide from structured data.

Single source of truth = each class's `meta.yml` + its `ideal/` and
`challenging/` image folders. This script renders that data into:

  * classes/<id>/index.qmd   -> a page in the HTML website
  * guide.qmd                -> a single combined document for the PDF build

The slide deck (slides/training.qmd) is authored separately.

Do NOT hand-edit the generated *.qmd files — edit meta.yml and re-run:

    python scripts/build_pages.py

Requires: pyyaml  (pip install -r requirements.txt)
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

import yaml

IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".gif", ".webp"}
REPO_ROOT = Path(__file__).resolve().parent.parent
CLASSES_DIR = REPO_ROOT / "classes"

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/build_pages.py — do not edit by hand. "
    "Edit meta.yml and re-run the script. -->"
)


def collapse(text) -> str:
    """Collapse a YAML block scalar into a single clean line."""
    if text is None:
        return ""
    return " ".join(str(text).split())


def yaml_quote(text: str) -> str:
    """Make a string safe to sit inside double quotes in YAML front matter."""
    return collapse(text).replace('"', "'")


def find_images(class_dir: Path, subset: str) -> list[str]:
    folder = class_dir / subset
    if not folder.is_dir():
        return []
    files = [
        p.name
        for p in folder.iterdir()
        if p.is_file() and p.suffix.lower() in IMAGE_EXTS
    ]
    return sorted(files)


def image_grid(class_dir: Path, subset: str, meta: dict, path_prefix: str) -> str:
    """Render an image subset as a Quarto column layout of captioned figures."""
    names = find_images(class_dir, subset)
    if not names:
        return "_No images yet — add files to this folder._\n"
    notes = meta.get("image_notes") or {}
    ncol = min(3, len(names))
    lines = [f'::: {{layout-ncol="{ncol}"}}', ""]
    for name in names:
        rel = f"{subset}/{name}"
        caption = collapse(notes.get(rel, ""))
        src = f"{path_prefix}{rel}"
        lines.append(f"![{caption}]({src})")
        lines.append("")
    lines.append(":::")
    lines.append("")
    return "\n".join(lines)


def distinguishing_table(meta: dict) -> str:
    rows = meta.get("distinguishing_from") or []
    if not rows:
        return "_No look-alike classes recorded yet._\n"
    out = ["| Similar class | How to tell them apart |", "|---|---|"]
    for row in rows:
        cls = collapse(row.get("class", "")).replace("|", "\\|")
        note = collapse(row.get("note", "")).replace("|", "\\|")
        out.append(f"| **{cls}** | {note} |")
    out.append("")
    return "\n".join(out)


def references_list(meta: dict) -> str:
    refs = meta.get("references") or []
    if not refs:
        return "_No external references yet._\n"
    out = []
    for ref in refs:
        title = collapse(ref.get("title", "reference"))
        url = collapse(ref.get("url", ""))
        out.append(f"- [{title}]({url})" if url else f"- {title}")
    out.append("")
    return "\n".join(out)


def render_body(class_dir: Path, meta: dict, path_prefix: str) -> str:
    """Shared ##-level body used by both the web page and the PDF section."""
    optics = ", ".join(meta.get("optics") or []) or "unspecified"
    group = collapse(meta.get("group", "Unclassified"))
    parts = [
        f"**Group:** {group}  ·  **Optics:** {optics}",
        "",
        "## Defining characteristics",
        "",
        collapse(meta.get("defining_characteristics")),
        "",
        "## Distinguishing from similar classes",
        "",
        distinguishing_table(meta),
        "## Ideal images",
        "",
        image_grid(class_dir, "ideal", meta, path_prefix),
        "## Challenging images",
        "",
        image_grid(class_dir, "challenging", meta, path_prefix),
        "## References",
        "",
        references_list(meta),
    ]
    return "\n".join(parts)


def cover_image(class_dir: Path) -> str | None:
    for subset in ("ideal", "challenging"):
        imgs = find_images(class_dir, subset)
        if imgs:
            return f"{subset}/{imgs[0]}"
    return None


def load_classes() -> list[tuple[Path, dict]]:
    out = []
    for class_dir in sorted(CLASSES_DIR.iterdir()):
        if not class_dir.is_dir():
            continue
        if class_dir.name.startswith((".", "_")):
            continue
        meta_path = class_dir / "meta.yml"
        if not meta_path.exists():
            print(f"  ! skipping {class_dir.name}: no meta.yml", file=sys.stderr)
            continue
        with meta_path.open() as fh:
            meta = yaml.safe_load(fh) or {}
        out.append((class_dir, meta))
    return out


def write_class_page(class_dir: Path, meta: dict) -> None:
    display = collapse(meta.get("display_name", class_dir.name))
    subtitle = yaml_quote(meta.get("one_liner", ""))
    group = collapse(meta.get("group", "Unclassified"))
    cover = cover_image(class_dir)

    fm = [
        "---",
        f'title: "{display}"',
        f'subtitle: "{subtitle}"',
        f"categories: [{group}]",
    ]
    if cover:
        fm.append(f"image: {cover}")
    fm += ["---", "", GENERATED_BANNER, ""]

    body = render_body(class_dir, meta, path_prefix="")
    (class_dir / "index.qmd").write_text("\n".join(fm) + "\n" + body + "\n")


def write_guide_pdf(classes: list[tuple[Path, dict]]) -> None:
    fm = textwrap.dedent(
        """\
        ---
        title: "Planktivore Labelling Guide"
        subtitle: "Complete class reference"
        format:
          pdf:
            toc: true
            toc-depth: 2
            number-sections: true
            fig-pos: "H"
            geometry: margin=1in
        ---
        """
    )
    chunks = [fm, GENERATED_BANNER, ""]
    for class_dir, meta in classes:
        display = collapse(meta.get("display_name", class_dir.name))
        prefix = f"classes/{class_dir.name}/"
        chunks.append(f"\n# {display}\n")
        chunks.append(render_body(class_dir, meta, path_prefix=prefix))
    (REPO_ROOT / "guide.qmd").write_text("\n".join(chunks) + "\n")


# Preferred display order for functional groups; unknown groups fall in
# alphabetically after these, with catch-all buckets last. Groups only appear
# on a page once at least one class uses them ("as they come online").
GROUP_ORDER = [
    "Ciliates",
    "Coccolithophores",
    "Diatoms",
    "Dinoflagellates",
    "Flagellates",
    "Silicoflagellates",
    "Radiolaria",
    "Other",
    "Miscellaneous",
    "Unclassified",
]


def group_sort_key(name: str):
    return (GROUP_ORDER.index(name) if name in GROUP_ORDER else len(GROUP_ORDER),
            name.lower())


def grid_items(members: list[tuple[Path, dict]]) -> list[str]:
    """A `.quick-grid` fenced div of image + class-name tiles linking to pages."""
    lines = ["::: {.quick-grid}"]
    for class_dir, meta in members:
        display = collapse(meta.get("display_name", class_dir.name))
        cover = cover_image(class_dir)  # e.g. "ideal/xyz.png" or None
        href = f"classes/{class_dir.name}/index.qmd"
        if cover:
            src = f"classes/{class_dir.name}/{cover}"
            lines.append(f"[![{display}]({src}){{.qg-img}} {display}]({href}){{.qg-item}}")
        else:
            # No image yet — show a placeholder tile so the class is still
            # visible and clickable, and the grid stays aligned.
            lines.append(
                f'[<span class="qg-img qg-noimg">no image yet</span> {display}]'
                f"({href}){{.qg-item}}"
            )
        lines.append("")  # blank line -> each item is its own grid cell
    lines.append(":::")
    lines.append("")
    return lines


def group_classes(classes: list[tuple[Path, dict]]) -> list[tuple[str, list]]:
    """Group classes by functional group, ordered; members sorted by name."""
    from collections import defaultdict

    groups: dict[str, list[tuple[Path, dict]]] = defaultdict(list)
    for class_dir, meta in classes:
        groups[collapse(meta.get("group", "Unclassified"))].append((class_dir, meta))
    out = []
    for group in sorted(groups, key=group_sort_key):
        members = sorted(
            groups[group],
            key=lambda cm: collapse(cm[1].get("display_name", cm[0].name)).lower(),
        )
        out.append((group, members))
    return out


def write_home(classes: list[tuple[Path, dict]]) -> None:
    """Home page: image + class name, wrapped in functional-group sections."""
    parts = [
        "---",
        'title: "Planktivore Labelling Guide"',
        "toc: false",
        "---",
        "",
        GENERATED_BANNER,
        "",
        "A visual reference for annotating [Planktivore](about.qmd) plankton images."
        " Click any specimen for its defining characteristics, look-alikes, and more examples.",
        "",
    ]
    for group, members in group_classes(classes):
        parts.append(f"## {group}")
        parts.append("")
        parts.extend(grid_items(members))
    (REPO_ROOT / "index.qmd").write_text("\n".join(parts) + "\n")


def write_quick_guide(classes: list[tuple[Path, dict]]) -> None:
    """A minimal flat specimen wall: one image + class name per class."""
    members = sorted(
        classes,
        key=lambda cm: collapse(cm[1].get("display_name", cm[0].name)).lower(),
    )
    parts = [
        "---",
        'title: "Quick guide"',
        "toc: false",
        "---",
        "",
        GENERATED_BANNER,
        "",
    ]
    parts.extend(grid_items(members))
    (REPO_ROOT / "quick-guide.qmd").write_text("\n".join(parts) + "\n")


def main() -> int:
    classes = load_classes()
    if not classes:
        print("No classes found under classes/.", file=sys.stderr)
        return 1
    for class_dir, meta in classes:
        write_class_page(class_dir, meta)
        print(f"  + classes/{class_dir.name}/index.qmd")
    write_guide_pdf(classes)
    print("  + guide.qmd")
    write_home(classes)
    print("  + index.qmd")
    write_quick_guide(classes)
    print("  + quick-guide.qmd")
    print(f"Done: {len(classes)} class(es).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
